name: Deploy to o2switch
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploiement FTP sur o2switch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Deploiement FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.ciho6017.odns.fr
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./
          server-dir: /public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/README.md
            **/.env.php
            **/.github/**
      - name: Deploiement termine
        run: echo "Site deploye avec succes via FTP !"
